Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable

Layout/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "pusher-push-notifications.gemspec"
