name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    env:
      PUSHER_INSTANCE_ID: 1b880590-6301-4bb5-b34f-45db1c5f5644
      PUSHER_SECRET_KEY: abc
        
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
